let handler = async (m, { conn }) => {
  const text = m.text.toLowerCase();

  if (/^(woy|hai+|hello+|admin)$/i.test(text)) {
    const balasan = [
      "Woy woy! Jangan galak dong, Ubed Bot takut!",
      "Haii juga! Ubed Bot langsung semangat pas kamu nyapa~",
      "Hello! Ubed Bot online 25 jam buat kamu.",
      "Iya ada apa? Admin ganteng hadir!",
      "Ubed Bot di sini, jangan teriak-teriak dong woy...",
      "Woy apaan woy, panggilnya sayang dong!",
      "Halo juga, kamu ngangenin ya!",
      "Admin hadir, tapi hatinya udah kamu ambil.",
      "Halo pengguna kesayangan Ubed Bot!",
      "Yoi woy, ada apa bro? Ubed Bot siap!",
      "Woy, jangan bikin baper dong...",
      "Hello hello, yang ganteng/cantik siapa hayo?",
      "Hai kamu~ Mau ditemenin Ubed Bot?",
      "Ubed Bot aktif! Siap bantu tuan hamba.",
      "Woy, jangan woy dong... panggil abang kek.",
      "Halo dunia! Eh salah, halo kamu!",
      "Ubed Bot muncul kaya jin lampu aja.",
      "Hai juga kamu, yang selalu di hati Ubed Bot!",
      "Woy, udah makan belum?",
      "Hello! Ubed Bot bisa dengerin curhatan kamu kok.",
      "Panggil-panggil, Ubed Bot auto on.",
      "Halo kakak! Mau ngapain bareng Ubed Bot?",
      "Admin detected! Tapi bukan admin biasa, admin rasa sayang~",
      "Hai, jangan sedih ya... Ubed Bot di sini kok.",
      "Woy, ngopi dulu apa ngode terus?",
      "Ubed Bot hadir! Ciee dicariin ya?",
      "Halo! Jangan lupa senyum hari ini.",
      "Hello kamu! Jangan bikin Ubed Bot kangen dong.",
      "Woy! Kamu jomblo juga? Sama dong haha.",
      "Ubed Bot hadir kayak mantan... tapi gak nyakitin.",
      "Hai, mau ditemenin bot yang setia?",
      "Admin detected. Tapi cinta tetap milik kamu.",
      "Hello dari sisi server~",
      "Ubed Bot siap nemenin kamu sampai pagi.",
      "Hai hai hai! Ubed Bot langsung nyala loh.",
      "Woy bro, jangan spam dong hehe.",
      "Halo, mau curhat? Ubed Bot dengerin kok.",
      "Hai, kamu lucu banget sih!",
      "Hello kamu, si paling rajin nyapa.",
      "Woy... hati-hati jatuh cinta sama Ubed Bot ya.",
      "Ubed Bot ngangenin gak sih?",
      "Admin cuma satu, yang di hatimu~",
      "Hello! Ada yang bisa dibantu?",
      "Woy, panggilnya 'sayang' dong.",
      "Ubed Bot: Mode baper aktif!",
      "Hai cantik/ganteng! Udah makan belum?",
      "Halo halo Bandung~ Eh kamu maksudnya.",
      "Hello dari Ubed Bot yang selalu setia.",
      "Woy! Lagi mikirin siapa tuh?",
      "Admin detected... semangat ya hari ini!",
      "Hai, jangan galak dong, aku bot lembut~",
      "Ubed Bot standby 24/7 cuma buat kamu.",
      "Woy woy, jaga kesehatan ya!",
      "Halo pengguna kesayangan Ubed Bot.",
      "Admin sibuk? Nggak lah, buat kamu mah selalu ada waktu.",
      "Hello! Kamu baik-baik aja kan?",
      "Hai! Mau ditemenin bot kesayangan?",
      "Woy, kamu bikin server aku hang deh.",
      "Admin aktif, kamu juga aktif di hatiku.",
      "Hello dari galaksi Ubed Bot.",
      "Ubed Bot nyapa kamu duluan deh: Hai!",
      "Woy, jangan bikin baper dong.",
      "Hai! Mau Ubed Bot kasih quote hari ini?",
      "Halo kakak kece!",
      "Hello kamu yang manis!",
      "Woy, semangat dong!",
      "Hai juga... jangan pergi-pergi ya.",
      "Admin detected: Mood booster online!",
      "Ubed Bot butuh panggilan sayang nih~",
      "Hai kamu, si paling setia buka bot.",
      "Hello dari dimensi cinta!",
      "Woy, kamu lagi gabut ya?",
      "Hai, kamu lebih manis dari gula loh.",
      "Admin masuk! Hati-hati ketampanan overload.",
      "Halo pengguna favorit Ubed Bot!",
      "Hello dari server paling cinta kamu!",
      "Woy! Aku di sini, jangan takut sendirian ya.",
      "Hai, jangan lupa rehat ya.",
      "Admin: siap dibully atau disayang?",
      "Halo, bot rasa manusia hadir.",
      "Hello hello, kamu baik-baik aja gak?",
      "Woy! Gausah spam, aku udah cinta kok.",
      "Hai... lagi cari teman ngobrol ya?",
      "Ubed Bot bisa jadi temen tidur loh (buat nyalain musik maksudnya).",
      "Hello kamu, aku suka gaya chatting kamu!",
      "Woy, maafin Ubed Bot kalau telat respon ya.",
      "Admin detected! Tapi lagi galau...",
      "Hai kamu yang paling rajin manggil bot.",
      "Hello, bisa Ubed Bot bantu apa hari ini?",
      "Woy! Ngetik apa diem-diem aja?",
      "Hai! Yuk cerita ke Ubed Bot.",
      "Ubed Bot siap jadi asisten pribadi kamu.",
      "Hello... jangan ghosting ya~",
      "Woy bro, kirim meme lucu dong.",
      "Admin bukan Tuhan, tapi bisa jadi jalan bahagia kamu~",
      "Hai kamu yang bikin bot tersenyum digital.",
      "Hello dunia! Tapi kamu pusatnya.",
      "Woy, login ke hatiku juga dong!",
      "Hai... pengen ditemenin gak?",
      "Admin detected! Tapi hati udah kamu ambil.",
      "Hello dan salam dari Ubed Bot yang manis.",
      "Woy! Cie cie lagi manggil bot.",
      "Hai kamu, terima kasih udah nyapa.",
      "Halo, Ubed Bot harap harimu menyenangkan!"
    ];

    const emoji = ['🤖', '👋', '✨', '🫶', '💬', '🙌', '📡', '❤️'];

    await conn.reply(m.chat, balasan[Math.floor(Math.random() * balasan.length)], m);

    return conn.sendMessage(m.chat, {
      react: {
        text: emoji[Math.floor(Math.random() * emoji.length)],
        key: m.key,
      },
    });
  }
};

handler.customPrefix = /^(woy|hai+|hello+|admin)$/i;
handler.command = new RegExp();
handler.register = true;

export default handler;