import axios from 'axios';

const handler = async (m, { conn, args, text, usedPrefix, command }) => {
  try {
    if (!text) {
      throw `Contoh penggunaan:\n${usedPrefix + command} print("Hello World")`;
    }

    await conn.sendMessage(m.chat, { react: { text: '🖌️', key: m.key } });

    const lang = 'python'; // Ganti jika ingin bahasa lain
    const api = `https://api.lolhuman.xyz/api/carbon?apikey=ubed2407&code=${encodeURIComponent(text)}&language=${lang}`;

    await conn.sendMessage(m.chat, {
      image: { url: api },
      caption: 'Generated by Ubed Bot'
    }, { quoted: m });

    await conn.sendMessage(m.chat, { react: { text: '✅', key: m.key } });

  } catch (err) {
    await conn.sendMessage(m.chat, { react: { text: '❌', key: m.key } });
    await conn.sendMessage(m.chat, {
      text: `Terjadi kesalahan: ${err.message || err}`
    }, { quoted: m });
  }
};

handler.help = ['carbon <kode>'];
handler.tags = ['maker'];
handler.command = ['carbon'];
handler.limit = true;

export default handler;